// Code generated by goctl. DO NOT EDIT.
package types

type AddOneTransactionRecordReq struct {
	TransactionDetailReq
}

type AddOneTransactionRecordResp struct {
	CommonResp
}

type CommonResp struct {
	Result  int    `json:"result"`
	Message string `json:"message,omitempty"` // omitempty: allow to omit
}

type ListAllTransactionRecordsReq struct {
}

type ListAllTransactionRecordsResp struct {
	CommonResp
	TransactionResults []TransactionRecordResult `json:"transaction_results"`
}

type ListOneTransactionRecordReq struct {
	StockCode string `form:"stock_code"` // 股票代码
	BuyDate   string `form:"buyDate"`    // 买入日期
}

type ListOneTransactionRecordResp struct {
	CommonResp
	TransactionResults []TransactionRecordResult `json:"transaction_results"`
}

type TransactionDetailReq struct {
	StockCode string  `form:"stock_code"` // 股票代码
	StockName string  `form:"stock_name"` // 股票名称
	BuyPrice  float64 `form:"buy_price"`  // 买入价格
	Number    float64 `form:"number"`     // 买入数量
	SellPrice float64 `form:"sell_price"` // 卖出价格
	BuyDate   string  `form:"buyDate"`    // 买入日期
	SellDate  string  `form:"sellDate"`   // 卖出日期
}

type TransactionDetailResp struct {
	StockCode string  `json:"stock_code"` // 股票代码
	StockName string  `json:"stock_name"` // 股票名称
	BuyPrice  float64 `json:"buy_price"`  // 买入价格
	Number    float64 `json:"number"`     // 买入数量
	SellPrice float64 `json:"sell_price"` // 卖出价格
	BuyDate   string  `json:"buyDate"`    // 买入日期
	SellDate  string  `json:"sellDate"`   // 卖出日期
}

type TransactionRecordResult struct {
	TransactionDetailResp
	TransactionResultResp
}

type TransactionResultResp struct {
	BuyCost     float64 `json:"buy_cost"`     // 买入费用
	SellCost    float64 `json:"sell_cost"`    // 卖出费用
	TotalCost   float64 `json:"total_cost"`   // 买卖总费用
	Rate        float64 `json:"rate"`         // 涨跌比例
	GainLoss    float64 `json:"gain_loss"`    // 持仓收益
	FinalProfit float64 `json:"final_profit"` // 最终收益
}
