// Code generated by goctl. DO NOT EDIT.
package types

type AddMarketTypeReq struct {
	MarketType string `form:"market_type"`
}

type AddMarketTypeResp struct {
	CommonResp
}

type CommonResp struct {
	Result  int    `json:"result"`
	Message string `json:"message,omitempty"` // omitempty: allow to omit
}

type ListMarketTypeReq struct {
}

type ListMarketTypeResp struct {
	CommonResp
	MarketType []string `json:"market_type"`
}
