// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"stock/cmd/transaction/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/addOneTransactionRecord",
				Handler: AddOneTransactionRecordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/listAllTransactionRecords",
				Handler: ListAllTransactionRecordsHandler(serverCtx),
			},
		},
	)
}
